market_events = [
    {"event_name": "Iraq War Concerns", "event_date": "2004-01-23", "event_type": "geopolitical", "severity": 2},
    {"event_name": "Housing Bubble Warnings", "event_date": "2006-05-10", "event_type": "macro", "severity": 2},
    {"event_name": "China Sell-Off", "event_date": "2007-02-27", "event_type": "global_market", "severity": 2},
    {"event_name": "Subprime Shock Begins", "event_date": "2007-08-09", "event_type": "credit", "severity": 3},
    {"event_name": "Bear Stearns Collapse", "event_date": "2008-03-17", "event_type": "banking", "severity": 3},
    {"event_name": "Lehman Brothers Bankruptcy", "event_date": "2008-09-15", "event_type": "banking", "severity": 3},
    {"event_name": "Obama Elected President", "event_date": "2008-11-04", "event_type": "political", "severity": 1},
    {"event_name": "Flash Crash", "event_date": "2010-05-06", "event_type": "market_structure", "severity": 3},
    {"event_name": "US Credit Rating Downgrade", "event_date": "2011-08-05", "event_type": "sovereign_credit", "severity": 3},
    {"event_name": "European Debt Crisis Peak", "event_date": "2012-06-11", "event_type": "sovereign_credit", "severity": 2},
    {"event_name": "Oil Crash Begins", "event_date": "2014-09-01", "event_type": "commodity", "severity": 2},
    {"event_name": "China Devaluation Crisis", "event_date": "2015-08-24", "event_type": "global_market", "severity": 3},
    {"event_name": "Brexit Referendum", "event_date": "2016-06-24", "event_type": "political", "severity": 2},
    {"event_name": "Trump Elected President", "event_date": "2016-11-08", "event_type": "political", "severity": 2},
    {"event_name": "Volatility Spike VIXplosion", "event_date": "2018-02-05", "event_type": "volatility", "severity": 3},
    {"event_name": "COVID Crash", "event_date": "2020-03-12", "event_type": "pandemic", "severity": 3},
    {"event_name": "Post-COVID Rally Peak", "event_date": "2021-11-19", "event_type": "market_cycle", "severity": 2},
    {"event_name": "Inflation Spike and Fed Hikes", "event_date": "2022-06-17", "event_type": "monetary_policy", "severity": 3},
    {"event_name": "SVB Bank Collapse", "event_date": "2023-03-10", "event_type": "banking", "severity": 3},
    {"event_name": "AI Tech Surge", "event_date": "2023-11-15", "event_type": "technology", "severity": 1},
    {"event_name": "2024 Election Cycle Begins", "event_date": "2024-03-01", "event_type": "political", "severity": 1},

    {"event_name": "Trump Liberation Day Tariffs", "event_date": "2025-04-02", "event_type": "tariff_trade", "severity": 3},
    {"event_name": "Trump Tariff Selloff", "event_date": "2025-04-03", "event_type": "tariff_trade", "severity": 3},
    {"event_name": "China Retaliatory Tariffs", "event_date": "2025-04-04", "event_type": "tariff_trade", "severity": 3},
    {"event_name": "Trump Black Monday", "event_date": "2025-04-07", "event_type": "tariff_trade", "severity": 3},
    {"event_name": "Trump Tariff Pause Rally", "event_date": "2025-04-09", "event_type": "tariff_trade", "severity": 2},
    {"event_name": "US-China Tariff Truce", "event_date": "2025-05-12", "event_type": "tariff_trade", "severity": 2},
    {"event_name": "US-EU Tariff Deal", "event_date": "2025-07-28", "event_type": "tariff_trade", "severity": 2},
    {"event_name": "US-China Truce Extension", "event_date": "2025-08-12", "event_type": "tariff_trade", "severity": 1},
    {"event_name": "China Rare Earth Controls", "event_date": "2025-10-09", "event_type": "tariff_trade", "severity": 2},
    {"event_name": "Trump-Xi Tariff Rare Earth Truce", "event_date": "2025-10-30", "event_type": "tariff_trade", "severity": 2},
    {"event_name": "Supreme Court Tariff Ruling", "event_date": "2026-02-20", "event_type": "legal_policy", "severity": 2},
    {"event_name": "Hormuz Oil Shock", "event_date": "2026-03-24", "event_type": "geopolitical", "severity": 3},
    {"event_name": "Trump EU Auto Tariff Threat", "event_date": "2026-05-01", "event_type": "tariff_trade", "severity": 2},
    {"event_name": "Trade Court Blocks Trump Tariffs", "event_date": "2026-05-07", "event_type": "legal_policy", "severity": 2},
    {"event_name": "Trump Rejects Iran Peace Proposal", "event_date": "2026-05-11", "event_type": "geopolitical", "severity": 2},
]